// Objective-C API for talking to github.com/algorand/go-algorand-sdk/utils Go package.
//   gobind -lang=objc github.com/algorand/go-algorand-sdk/utils
//
// File is generated by gobind. Do not edit.

#ifndef __Utils_H__
#define __Utils_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL UtilsIsValidAddress(NSString* _Nullable addr);

// skipped function PendingResultsToTXID with unsupported parameter or return types


#endif
